version: '3'
services:
  distbot-dev-ff:
    volumes:
    - .:/tests
    network_mode: "host"
    image: rajeevnaikte/distbot
    build: .
    command: -e dev -b headlessfirefox --mode distributed --max-cpu-percent 80 --max-memory 1024 examples -v USERNAME:lll -v PASSWORD:xxx
    
